import React,{useState} from 'react';
import {presets,layerSvg} from './canvas-elements.js';
import {scaleLayer} from './layer-transform.js';
export function CanvasLibrary({tool,add,close,busy}){if(!presets[tool])return null;return <section className="canvas-library"><header><strong>{tool==='text'?'Add text':tool==='shape'?'Shapes':'Components'}</strong><button aria-label="Close tool library" onClick={close}>&#215;</button></header><p>{tool==='text'?'Start with a type style.':tool==='shape'?'Simple forms. Endless combinations.':'Ready to make your own.'}</p><div className={'preset-list presets-'+tool}>{presets[tool].map(p=><button disabled={busy} key={p.name} onClick={()=>add(tool,undefined,p)}><span className="preset-preview" dangerouslySetInnerHTML={{__html:layerSvg({type:tool,color:'#344539',fontSize:24,width:240,height:160,...p})}}/><span>{p.name}</span></button>)}</div></section>}
export function FilterPanel({enabled,busy,target,onApply,onClose}){
 const [preset,setPreset]=useState('original'),[brightness,setBrightness]=useState(0),[contrast,setContrast]=useState(0),[saturation,setSaturation]=useState(0);
 return <section className="canvas-library filter-panel"><header><strong>Cloudinary filters</strong><button aria-label="Close filters" onClick={onClose}>&#215;</button></header><p>{target||'Generate or select an image to use filters.'}</p><fieldset disabled={busy||!enabled}><div className="filter-presets">{[['original','Original'],['mono','Mono'],['sepia','Sepia'],['vivid','Vivid'],['warm','Warm'],['cool','Cool'],['soft','Soft'],['sharpen','Crisp']].map(([id,name])=><button type="button" className={preset===id?'chosen':''} aria-pressed={preset===id} key={id} onClick={()=>setPreset(id)}><i className={'filter-chip chip-'+id}/>{name}</button>)}</div>{[['Brightness',brightness,setBrightness,-50,50],['Contrast',contrast,setContrast,-50,50],['Saturation',saturation,setSaturation,-100,100]].map(([name,value,set,min,max])=><label key={name}>{name}<output>{value>0?'+':''}{value}</output><input type="range" min={min} max={max} value={value} onChange={e=>set(Number(e.target.value))}/></label>)}<button className="primary full" disabled={preset==='original'&&!brightness&&!contrast&&!saturation} onClick={()=>onApply({preset,brightness,contrast,saturation})}>{busy?'Applying...':'Apply to whole image'}</button><button className="filter-reset" onClick={()=>{setPreset('original');setBrightness(0);setContrast(0);setSaturation(0);}}>Reset controls</button></fieldset><small>Filters always affect the whole scene image, regardless of the selected object. Use Undo to restore the previous version.</small></section>;
}
export function LayerProperties({element:e,update,remove,duplicate,arrange}){
 const text=e.type==='text'||e.type==='cube';
 return <section className="element-properties"><span className="eyebrow">LAYER PROPERTIES</span><h2>{e.name||({text:'Text',shape:'Shape',cube:'Component',image:'Image'}[e.type])}</h2>
 {text&&<><label>Text<textarea value={e.text} maxLength={2000} onChange={ev=>update({text:ev.target.value})}/></label>{e.type==='cube'&&!['button','badge'].includes(e.component)&&<label>Supporting text<textarea maxLength={500} value={e.body||''} onChange={ev=>update({body:ev.target.value})}/></label>}<label>Font family<select value={e.fontFamily||'Arial'} onChange={ev=>update({fontFamily:ev.target.value})}>{['Arial','Georgia','Verdana','Courier New'].map(f=><option key={f}>{f}</option>)}</select></label><div className="property-grid"><label>Size<input type="number" min="8" max="1024" value={e.fontSize} onChange={ev=>update({fontSize:Math.max(8,Math.min(1024,+ev.target.value))})}/></label><label>Weight<select value={e.fontWeight||400} onChange={ev=>update({fontWeight:+ev.target.value})}>{[[400,'Regular'],[500,'Medium'],[700,'Bold']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label></div><div className="property-toggles">{['left','center','right'].map(align=><button key={align} aria-pressed={(e.align||'left')===align} onClick={()=>update({align})}>{align}</button>)}<button aria-pressed={!!e.italic} onClick={()=>update({italic:!e.italic})}><em>Italic</em></button></div><label>Line spacing<input type="range" min="0.8" max="2" step="0.05" value={e.lineHeight||1.25} onChange={ev=>update({lineHeight:+ev.target.value})}/></label></>}
 {e.type==='shape'&&<label>Shape<select value={e.shape||'rectangle'} onChange={ev=>update({shape:ev.target.value})}>{presets.shape.map(s=><option key={s.shape} value={s.shape}>{s.name}</option>)}</select></label>}
 <section className="scale-controls"><label>Scale <span>Proportional</span><div><button type="button" aria-label="Scale down" onClick={()=>update(scaleLayer(e,0.9))}>-</button><input type="number" aria-label="Layer scale percent" min="1" max="4000" step="5" value={Math.round((e.scale||1)*100)} onChange={ev=>{const percent=Number(ev.target.value);if(percent>0)update(scaleLayer(e,percent/100/(e.scale||1)));}}/><span>%</span><button type="button" aria-label="Scale up" onClick={()=>update(scaleLayer(e,1.1))}>+</button></div></label><p>Drag corners to scale, or edges to resize the container. Hold Shift for free proportions.</p></section>
 <div className="property-grid">{['x','y','width','height'].map(k=><label key={k}>{k}<input type="number" min={['width','height'].includes(k)?10:0} max="4000" value={Math.round(e[k])} onChange={ev=>update({[k]:Math.max(['width','height'].includes(k)?10:0,Math.min(4000,+ev.target.value))})}/></label>)}</div>
 {e.type!=='image'&&<label>{text?'Text color':'Fill'}<input type="color" value={e.color} onChange={ev=>update({color:ev.target.value})}/></label>}
 {e.type==='cube'&&<label>Background<input type="color" value={e.background||'#f0f2f4'} onChange={ev=>update({background:ev.target.value})}/></label>}
 {e.type==='shape'&&<div className="property-grid"><label>Outline<input type="color" value={e.stroke||'#354a3b'} onChange={ev=>update({stroke:ev.target.value})}/></label><label>Width<input type="number" min="0" max="20" value={e.strokeWidth||0} onChange={ev=>update({strokeWidth:Math.max(0,Math.min(20,+ev.target.value))})}/></label></div>}
 <label>Rotation <output>{e.rotation||0} degrees</output><input type="range" min="-180" max="180" value={e.rotation||0} onChange={ev=>update({rotation:+ev.target.value})}/></label><label>Corner radius<input type="range" min="0" max="100" value={e.radius} onChange={ev=>update({radius:+ev.target.value})}/></label><label>Opacity<input type="range" min="0.05" max="1" step="0.05" value={e.opacity} onChange={ev=>update({opacity:+ev.target.value})}/></label><div className="layer-actions"><button onClick={duplicate}>Duplicate</button><button onClick={()=>arrange('front')}>To front</button><button onClick={()=>arrange('back')}>To back</button><button onClick={remove}>Delete</button></div></section>;
}
