import React,{useEffect,useRef,useState} from 'react';
import {directionOptions,defaultDirection,directionChoices} from './direction.js';
export default function CreativeDirection({value,onApply,onClose}){
 const [draft,setDraft]=useState(value);const dialog=useRef(null);
 useEffect(()=>{dialog.current.showModal();},[]);
 const choices=directionChoices(draft),palette=directionOptions.palette.find(p=>p.id===draft.palette);
 return <dialog ref={dialog} className="direction-dialog" aria-labelledby="direction-title" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}>
  <header className="direction-header"><div><span className="direction-kicker">MAKE IT FEEL LIKE YOU</span><h2 id="direction-title">Creative direction</h2><p>Your idea sets the subject. These choices set the feeling.</p></div><button autoFocus type="button" aria-label="Close creative direction" onClick={onClose} className="direction-close">&#215;</button></header>
  <div className="direction-body"><div className="direction-fields">
   <fieldset><legend>Visual style <span>01</span></legend><div className="direction-style-grid">{directionOptions.style.map(option=><button type="button" key={option.id} className={'direction-style '+(draft.style===option.id?'chosen':'')} aria-pressed={draft.style===option.id} onClick={()=>setDraft({...draft,style:option.id})}><span className={'style-art style-art-'+option.id} aria-hidden="true"><i/><i/><i/></span><span className="style-name">{option.name}</span><small>{option.hint}</small><span className="direction-check" aria-hidden="true">{draft.style===option.id?'\u2713':''}</span></button>)}</div></fieldset>
   <fieldset><legend>Color palette <span>02</span></legend><div className="direction-palette-grid">{directionOptions.palette.map(option=><button type="button" key={option.id} aria-pressed={draft.palette===option.id} className={draft.palette===option.id?'chosen':''} onClick={()=>setDraft({...draft,palette:option.id})}><span className="palette-swatches" aria-hidden="true">{option.colors.map(color=><i key={color} style={{background:color}}/>)}</span>{option.name}</button>)}</div></fieldset>
   {['lighting','composition'].map((key,index)=><fieldset key={key}><legend>{key==='lighting'?'Lighting & mood':'Composition'}<span>0{index+3}</span></legend><div className="direction-pills">{directionOptions[key].map(option=><button type="button" key={option.id} aria-pressed={draft[key]===option.id} className={draft[key]===option.id?'chosen':''} onClick={()=>setDraft({...draft,[key]:option.id})}>{option.name}</button>)}</div></fieldset>)}
  </div><aside className="direction-preview"><span className="direction-kicker">YOUR DIRECTION</span><div className={'direction-moodboard mood-'+draft.style+' light-'+draft.lighting+' layout-'+draft.composition} style={{'--swatch-a':palette.colors[0],'--swatch-b':palette.colors[1],'--swatch-c':palette.colors[2]}} aria-hidden="true"><div className="mood-orbit"/><div className="mood-object"/><div className="mood-line"/><span>Form<br/><em>& feeling.</em></span></div><span className="direction-preview-caption">A mood study, not a generated preview</span><h3>{choices.length?'A little more intentional.':'Room for possibility.'}</h3><p>{choices.length?'Your preferences will guide the next image you create.':'Leave any setting on Automatic to let your prompt lead.'}</p><div className="direction-summary">{choices.length?choices.map(o=><div key={o.key}><span>{o.key}</span><strong>{o.name}</strong></div>):<span>Guided by your prompt</span>}</div></aside></div>
  <footer className="direction-footer"><button type="button" className="direction-reset" onClick={()=>setDraft({...defaultDirection})}>Reset to automatic</button><div><button type="button" onClick={onClose}>Cancel</button><button type="button" className="primary" onClick={()=>onApply(draft)}>Apply direction <span aria-hidden="true">&#8599;</span></button></div></footer>
 </dialog>;
}
