import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {Home,Icon,ToolDock} from './Studio.jsx';
import './studio.css';
import {CanvasLibrary,FilterPanel,LayerProperties} from './CanvasLibrary.jsx';
import {layerSvg} from './canvas-elements.js';
import {resizeLayer,resizeHandles} from './layer-transform.js';
async function api(url,body,method){const response=await fetch('/api'+url,{method:method||(body?'POST':'GET'),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await response.json();}catch{throw new Error('The server is unavailable. Check that the backend is running.');}if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
function App(){
 const [config,setConfig]=useState(null),[scene,setScene]=useState(null),[prompt,setPrompt]=useState(()=>localStorage.getItem('reframe-prompt')||''),[selected,setSelected]=useState(null),[hovered,setHovered]=useState(null),[mode,setMode]=useState('Edit'),[instruction,setInstruction]=useState(''),[plan,setPlan]=useState(null),[box,setBox]=useState(null),[busy,setBusy]=useState(false),[job,setJob]=useState(null),[status,setStatus]=useState('Ready for your first scene'),[error,setError]=useState(''),[compare,setCompare]=useState(50),[newScene,setNewScene]=useState(false);
 const [view,setView]=useState(new URLSearchParams(location.search).has('scene')?'canvas':'home'),[leaving,setLeaving]=useState(false),[activePrompt,setActivePrompt]=useState(()=>localStorage.getItem('reframe-active-prompt')||''),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[tool,setTool]=useState('select'),[preview,setPreview]=useState(false),[layers,setLayers]=useState([]),[layerId,setLayerId]=useState(null),[past,setPast]=useState([]),[future,setFuture]=useState([]),[notice]=useState('');
 const viewportRef=useRef(null),gesture=useRef(null),transitionRef=useRef(null),submitting=useRef(false);
 useEffect(()=>()=>clearTimeout(transitionRef.current),[]);
 useEffect(()=>{localStorage.setItem('reframe-prompt',prompt);},[prompt]);
 useEffect(()=>{localStorage.setItem('reframe-active-prompt',activePrompt);},[activePrompt]);
 function fitCanvas(){const el=viewportRef.current;if(!el)return;const width=scene?.width||1200,height=scene?.height||800;const scale=Math.min(1,Math.max(.1,Math.min((el.clientWidth-48)/width,(el.clientHeight-48)/height)));setZoom(scale);setPan({x:(el.clientWidth-width*scale)/2-20,y:(el.clientHeight-height*scale)/2-20});}
 useEffect(()=>{if(view!=='canvas')return;const el=viewportRef.current;if(!el)return;const observer=new ResizeObserver(fitCanvas);observer.observe(el);fitCanvas();return()=>observer.disconnect();},[view,scene?.id,preview]);
 const activeLayer=layers.find(l=>l.id===layerId);
 const [layerPlan,setLayerPlan]=useState(null);
 useEffect(()=>{setLayerPlan(null);setPlan(null);setPrepared(null);},[layerId,activeLayer?.src]);
 const editableImage=activeLayer?.type==='image';
 async function prepareLayer(applyNow=false){await run(async()=>{
   const target=activeLayer;
   setStatus('Preparing the selected image');setLayerPlan(null);
   let imported;
   {
     const blob=await (await fetch(target.src)).blob();
     const response=await fetch('/api/layer-images',{method:'POST',headers:{'Content-Type':blob.type},body:blob});
     const data=await response.json();if(!response.ok)throw new Error(data.error||'Image upload failed.');imported=data;
     setLayers(ls=>ls.map(l=>l.id===target.id?{...l,imageSceneId:imported.id}:l));
   }
   setStatus('Preparing your image edit for review');
   const p=await api('/scenes/'+imported.id+'/plan',{instruction,selectedId:imported.versions[imported.current].entities[0].id});
   const nextPlan={...p,layerId:target.id,source:target.src};
   if(applyNow){await renderLayer(nextPlan);return;}
   setLayerPlan(nextPlan);setStatus('Ready for review. No image has been changed yet.');
 });}
 async function renderLayer(p){
   setStatus('Rendering your image edit');const j=await api('/scenes/'+p.sceneId+'/edit',{planId:p.planId,box:p.box||p.entity.box});
   await watch(j.jobId,async updated=>{const v=updated.versions[updated.current];if(v.id===p.versionId)throw new Error('No edited image was returned. Your original is unchanged.');await loadImage(v.url);commit(layers.map(l=>l.id===p.layerId?{...l,src:v.url,imageSceneId:updated.id}:l));});
   setLayerPlan(null);setInstruction('');setStatus('New image version ready. Other layers are unchanged.');
 }
 async function applyLayer(){const p=layerPlan;if(!p||activeLayer?.id!==p.layerId||activeLayer.src!==p.source)return;await run(()=>renderLayer(p));}
 async function loadImage(url){const image=new Image();image.src=url;await image.decode();}
 async function renderSceneEdit(p,approvedBox){
   setStatus('Rendering your edit to '+p.entity.name);const j=await api('/scenes/'+p.sceneId+'/edit',{planId:p.planId,box:approvedBox});
   await watch(j.jobId,async updated=>{const v=updated.versions[updated.current];if(v.id===p.versionId)throw new Error('No edited image was returned. Your original is unchanged.');await loadImage(v.url);recordHistory();setScene(updated);});
   setMode('Edit');setPreview(false);setPlan(null);setPrepared(null);setInstruction('');setStatus('New image version ready. Use Compare to inspect the change.');
 }
 async function changeSelectedImage(){
   if(busy||instruction.trim().length<3)return;
   if(editableImage)return prepareLayer(true);
   if(!scene)return;
   await run(async()=>{setPlan(null);setPrepared(null);setStatus('Preparing your requested change');const p=await api('/scenes/'+scene.id+'/plan',{instruction,selectedId:selected});setSelected(p.targetEntity);await renderSceneEdit(p,p.box||p.entity.box);});
 }

 function snapshot(previousLayers=layers){return {layers:previousLayers,sceneId:scene?.id,versionId:current?.id};}
 function recordHistory(){setPast(p=>[...p.slice(-49),snapshot()]);setFuture([]);}
 function commit(next){recordHistory();setLayers(next);}
 async function historyStep(direction){if(busy)return;await run(async()=>{
   const undo=direction==='undo',stack=undo?past:future;
   let target=undo?stack.at(-1):stack[0];
   if(!target){const versionId=undo?current?.parentId:scene?.versions[scene.current+1]?.id;if(!versionId)return;target={...snapshot(),versionId};}
   const before=snapshot();
   if(target.sceneId&&target.sceneId===scene?.id&&target.versionId!==current?.id)setScene(await api('/scenes/'+scene.id+'/restore',{versionId:target.versionId}));
   setLayers(target.layers);setLayerId(null);setSelected(null);setPlan(null);setMode('Edit');
   if(undo){setPast(p=>p.slice(0,-1));setFuture(f=>[before,...f]);}else{setFuture(f=>f.slice(1));setPast(p=>[...p.slice(-49),before]);}
   setStatus(undo?'Last change undone.':'Change restored.');
 });}
 function add(type,src,options={}){const id=crypto.randomUUID();commit([...layers,{id,type,src,text:type==='cube'?'Make something great':'Your text',x:100+layers.length*20,y:90+layers.length*20,width:type==='text'?320:240,height:type==='text'?80:160,color:type==='shape'?'#d9e4e0':'#202124',fontSize:32,radius:type==='cube'?16:0,opacity:1,fontFamily:'Arial',fontWeight:400,align:'left',lineHeight:1.25,rotation:0,...options}]);setLayerId(id);setSelected(null);setTool('select');}
 async function upload(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('Choose a PNG, JPEG or WebP image smaller than 10 MB.');return;}const reader=new FileReader();reader.onload=()=>{add('image',reader.result);setView('canvas');};reader.onerror=()=>setError('This image could not be opened.');reader.readAsDataURL(file);}
 async function enter(generationPrompt=prompt){if(submitting.current||busy||!prompt.trim())return;if(prompt.trim().length<10){setError('Describe your idea in at least 10 characters.');return;}if(!canGenerate){setError('Image generation is not configured. You can still upload an image to start editing.');return;}submitting.current=true;setActivePrompt(generationPrompt.trim());setError('');setLeaving(true);transitionRef.current=setTimeout(()=>{setView('canvas');setLeaving(false);setScene(null);setLayers([]);setPast([]);setFuture([]);setPan({x:0,y:0});setZoom(1);generate(generationPrompt).finally(()=>{submitting.current=false;});},650);}
 function beginDrag(e,id){if(preview||busy)return;if(tool==='move'){gesture.current={kind:'pan',x:e.clientX,y:e.clientY,start:pan};}else if(id){setLayerId(id);setSelected(null);gesture.current={kind:'layer',id,x:e.clientX,y:e.clientY,start:layers.find(l=>l.id===id),before:layers};}else return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);}
 function beginResize(e,id,handle){if(preview||busy)return;e.preventDefault();e.stopPropagation();const layer=layers.find(l=>l.id===id);gesture.current={kind:'resize',id,handle,x:e.clientX,y:e.clientY,start:layer,before:layers};e.currentTarget.setPointerCapture(e.pointerId);}
 function drag(e){const g=gesture.current;if(!g)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;g.changed=!!(dx||dy);if(g.kind==='pan')setPan({x:g.start.x+dx,y:g.start.y+dy});else if(g.kind==='resize')setLayers(ls=>ls.map(l=>l.id===g.id?resizeLayer(g.start,g.handle,dx/zoom,dy/zoom,e.shiftKey):l));else setLayers(ls=>ls.map(l=>l.id===g.id?{...l,x:Math.max(0,g.start.x+dx/zoom),y:Math.max(0,g.start.y+dy/zoom)}:l));}
 function endDrag(){const g=gesture.current;if(g?.changed&&(g.kind==='layer'||g.kind==='resize')){setPast(p=>[...p.slice(-49),snapshot(g.before)]);setFuture([]);}gesture.current=null;}
 function cancelDrag(){const g=gesture.current;if(g?.before)setLayers(g.before);else if(g?.kind==='pan')setPan(g.start);gesture.current=null;}
 function keyboardResize(e,layer,handle){if(busy||preview)return;const moves={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!moves[e.key])return;e.preventDefault();e.stopPropagation();const [dx,dy]=moves[e.key],step=e.altKey?10:1;commit(layers.map(l=>l.id===layer.id?resizeLayer(l,handle,dx*step,dy*step,e.shiftKey):l));}

 async function exportCanvas(){await safe(async()=>{const w=scene?.width||1200,h=scene?.height||800,c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);async function draw(src,x,y,width,height){const image=new Image();image.src=src;await image.decode();ctx.drawImage(image,x,y,width,height);}if(current)await draw(current.url,0,0,w,h);for(const l of layers){ctx.save();ctx.globalAlpha=l.opacity;ctx.translate(l.x+l.width/2,l.y+l.height/2);ctx.rotate((l.rotation||0)*Math.PI/180);ctx.translate(-l.width/2,-l.height/2);ctx.beginPath();ctx.roundRect(0,0,l.width,l.height,l.radius);ctx.clip();if(l.type==='image')await draw(l.src,0,0,l.width,l.height);else{const url=URL.createObjectURL(new Blob([layerSvg(l)],{type:'image/svg+xml'}));try{await draw(url,0,0,l.width,l.height);}finally{URL.revokeObjectURL(url);}}ctx.restore();}const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw new Error('Could not export Canvas.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reframe-canvas.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Canvas exported as PNG.');});}
 async function applyFilter(settings){if(!scene||busy)return;await run(async()=>{
  setStatus('Applying Cloudinary filter to the whole image');
  const response=await api('/scenes/'+scene.id+'/filter',{...settings,versionId:scene.versions[scene.current].id});
  await watch(response.jobId,async updated=>{const v=updated.versions[updated.current];await loadImage(v.url);recordHistory();setScene(updated);setMode('Edit');});
  setStatus('Filter applied to the whole image. Use Undo to restore the previous version.');
 });}

 const current=scene?.versions[scene.current],entities=current?.entities||[],entity=entities.find(e=>e.id===selected),highlight=entities.find(e=>e.id===(hovered||selected));
 async function safe(fn){setError('');try{return await fn();}catch(e){setError(e.message);}}
 async function initialize(){await safe(async()=>{setConfig(await api('/config'));const saved=new URLSearchParams(window.location.search).get('scene')||localStorage.getItem('reframe-scene');if(saved){try{const restored=await api('/scenes/'+saved);setScene(restored);if(new URLSearchParams(location.search).has('scene')||!localStorage.getItem('reframe-active-prompt'))setActivePrompt(restored.prompt||restored.versions[0]?.provenance?.prompt||'');}catch{localStorage.removeItem('reframe-scene');}}});}
 useEffect(()=>{initialize();},[]);
 useEffect(()=>{if(scene)localStorage.setItem('reframe-scene',scene.id);},[scene]);
 useEffect(()=>{setPlan(null);setBox(entity?.box||null);},[selected,current?.id]);
 async function watch(jobId,onScene=setScene){setJob(jobId);for(;;){await new Promise(r=>setTimeout(r,1000));const j=await api('/jobs/'+jobId);setStatus(j.stage);if(j.status!=='running'){let completed;if(j.sceneId){completed=await api('/scenes/'+j.sceneId);await onScene(completed);}if(completed?.analysisWarning)setError(completed.analysisWarning);setJob(null);if(j.status!=='complete')throw new Error(j.error||'Operation cancelled.');return completed;}}}
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);setStatus('Operation stopped. Your prompt is preserved.');}finally{setBusy(false);setJob(null);}}
 async function generate(generationPrompt=prompt){if(typeof generationPrompt!=='string')generationPrompt=prompt;await run(async()=>{setStatus('Submitting scene');setActivePrompt(generationPrompt.trim());const j=await api('/scenes',{prompt:generationPrompt});setNewScene(false);setSelected(null);setPlan(null);const completed=await watch(j.jobId);setStatus(completed?.versions[completed.current].entities.length?'Scene ready. Select a region to edit.':'Image saved. Retry region analysis to create editable regions.');});}
 // Selection's effect clears old plans; restore the newly prepared plan after selection settles.
 const [prepared,setPrepared]=useState(null);
 async function prepareStable(){if(editableImage)return prepareLayer(false);await run(async()=>{setPlan(null);setPrepared(null);setStatus('Interpreting your edit with MiniMax M3');const p=await api('/scenes/'+scene.id+'/plan',{instruction,selectedId:selected});setSelected(p.targetEntity);setPrepared(p);setStatus('Ready for review. No image has been changed yet.');});}
 useEffect(()=>{if(prepared&&!activeLayer&&selected===prepared.targetEntity){setPlan(prepared);setBox(prepared.box||prepared.entity.box);setPrepared(null);}},[prepared,selected,layerId]);
 async function apply(){if(!plan||!box)return;await run(()=>renderSceneEdit(plan,box));}
 async function restore(versionId){await run(async()=>{const restored=await api('/scenes/'+scene.id+'/restore',{versionId});recordHistory();setScene(restored);setPlan(null);setStatus('Saved version restored.');});}
 const canGenerate=config?.hy.ready&&config?.minimax;
 function select(id){if(!busy){setLayerId(null);setSelected(id);setPlan(null);}}
 function regionStyle(b){return {left:b.x*100+'%',top:b.y*100+'%',width:b.width*100+'%',height:b.height*100+'%'};}
 function hit(e){const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;return entities.filter(o=>!o.removed&&x>=o.box.x&&x<=o.box.x+o.box.width&&y>=o.box.y&&y<=o.box.y+o.box.height).sort((a,b)=>a.box.width*a.box.height-b.box.width*b.box.height)[0];}
 if(view==='home')return <Home prompt={prompt} setPrompt={setPrompt} onSubmit={enter} leaving={leaving} busy={busy||leaving} ready={!!config} error={error} notice={notice} onResume={()=>setView('canvas')} hasScene={!!scene||layers.length>0} onUpload={upload}/>;
 return <div className={'app studio '+(preview?'preview-mode':'')}>
 
  <header className="topbar"><button className="brand brand-button" aria-label="Reframe home" disabled={busy} onClick={()=>setView('home')}><span className="mark"/>Reframe</button><div className="project-name">{scene?.title||'Untitled project'}<span>Canvas / {busy?'Generating':'All ideas welcome'}</span></div><div className="history-actions"><button aria-label="Undo" title="Undo" disabled={busy||(!past.length&&!current?.parentId)} onClick={()=>historyStep('undo')}><Icon name="undo"/></button><button aria-label="Redo" title="Redo" disabled={busy||(!future.length&&!(scene&&scene.current<scene.versions.length-1))} onClick={()=>historyStep('redo')}><Icon name="redo"/></button></div><div className="zoom-controls"><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.1,z-.1))}>-</button><button title="Fit canvas to view" onClick={fitCanvas}>{Math.round(zoom*100)}%</button><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(3,z+.1))}>+</button></div><div className="top-actions"><button aria-pressed={preview} onClick={()=>setPreview(p=>!p)}><Icon name="eye"/><span>Preview</span></button><button disabled={!scene||layers.length>0} title={layers.length?'Export PNG to share your added layers':'Copy link to this saved scene'} onClick={()=>safe(async()=>{const url=new URL(location.href);url.searchParams.set('scene',scene.id);await navigator.clipboard.writeText(url.href);setStatus('Scene link copied. Recipients need workspace access.');})}>Share</button><button className="primary" disabled={busy||(!current&&!layers.length)} onClick={exportCanvas}><Icon name="export"/><span>Export</span></button></div></header>
  <div className="workspace">
   <aside className="entities-panel"><ToolDock tool={tool} setTool={setTool} busy={busy}/><CanvasLibrary tool={tool} add={add} close={()=>setTool('select')} busy={busy}/>{tool==='settings'&&<FilterPanel enabled={!!config?.cloudinary&&!!scene} busy={busy} target={scene?'Whole image / selection does not affect filters':'Generate an image to apply filters'} onApply={applyFilter} onClose={()=>setTool('select')}/>}<div className="panel-heading"><span>LAYERS</span><span className="count">{(entities.filter(e=>!e.removed).length+layers.length).toString().padStart(2,'0')}</span></div>
    <div className="scene-label"><span className="tiny-frame"/> {scene?'Generated scene':'Your scene starts here'}</div>
    <div className="entity-list">{layers.map(l=><button key={l.id} disabled={busy} className={"entity-row "+(l.id===layerId?"selected":"")} onClick={()=>{setLayerId(l.id);setSelected(null);}}><Icon name={l.type}/><span>{l.type==='text'||l.type==='cube'?l.text:l.type==='image'?'Image':l.name||'Shape'}</span></button>)}{entities.length?entities.map((e,i)=><button key={e.id} disabled={busy} className={'entity-row '+(selected===e.id?'selected ':'')+(e.removed?'removed':'')} onClick={()=>select(e.id)} onMouseEnter={()=>setHovered(e.id)} onMouseLeave={()=>setHovered(null)} aria-pressed={selected===e.id}><span className="entity-number">{String(i+1).padStart(2,'0')}</span><span>{e.name}<small>{e.removed?'Removed':e.type}</small></span><span className="entity-dot"/></button>):layers.length?null:<div className="empty-entities"><div className="layer-symbol"><i/><i/><i/></div><p>A scene, with structure.</p><small>After generation, visible objects will appear here as editable regions.</small></div>}</div>
    <div className="panel-foot"><span className="status-dot"/><span>{entities.length?'Image-derived regions':'No entities detected yet'}</span><p>Understand · Select · Reframe</p></div>
   </aside>
   <main className="canvas-panel"><div className="canvas-toolbar"><div className="tabs">{['Edit','Inspect','Compare','Scene map'].map(m=><button key={m} disabled={!scene||busy} onClick={()=>setMode(m)} className={mode===m?'active':''}>{m}</button>)}</div><span className="canvas-dimensions">{scene?scene.width+' × '+scene.height:'SCENE CANVAS'}</span></div>
    <div ref={viewportRef} className={'canvas-area '+(!scene?'is-empty ':'')+(tool==='move'?'panning':'')} onPointerDown={e=>beginDrag(e,null)} onPointerMove={drag} onPointerUp={endDrag} onPointerCancel={cancelDrag} onWheel={e=>{if(e.ctrlKey||e.metaKey)setZoom(z=>Math.max(.1,Math.min(3,z-e.deltaY*.002)));else setPan(p=>({x:p.x-e.deltaX,y:p.y-e.deltaY}));}}>
     <div className="canvas-stage" style={{width:scene?.width||1200,height:scene?.height||800,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
    {!scene?<div className="generation-empty">{busy?<><span className="large-spinner"/><h2>Your idea is taking shape.</h2><p>{status}</p><blockquote>{activePrompt}</blockquote></>:layers.length?null:<><Icon name="cube" width="36" height="36"/><h2>A little space for a big idea.</h2><p>Add text, shapes or an image. Or generate something new.</p><button onClick={()=>{setView('home');setError('');}}>Describe your idea <span aria-hidden="true">&#8599;</span></button></>}</div>:
     mode==='Scene map'?<div className="scene-map"><span className="eyebrow">SPATIAL SCENE MAP · APPROXIMATE REGIONS</span><div className="map-surface" style={{aspectRatio:scene.width+'/'+scene.height}}>{entities.filter(e=>!e.removed).map(e=><button key={e.id} style={regionStyle(e.box)} onClick={()=>select(e.id)} className={selected===e.id?'chosen':''}>{e.name}<small>Depth {e.depth}</small></button>)}</div><p>Placement reflects image regions. Select an entity to inspect its relationships.</p></div>:
     <div className="artwork-wrap"><div className="artwork" style={{aspectRatio:scene.width+'/'+scene.height}} onMouseMove={e=>mode==='Inspect'&&setHovered(hit(e)?.id||null)} onMouseLeave={()=>setHovered(null)} onClick={e=>tool!=='move'&&mode!=='Compare'&&select(hit(e)?.id||null)}><img src={current.url} alt={scene.title} draggable="false"/>
       {mode==='Compare'&&<><img className="original-overlay" src={scene.versions[0].url} alt="Original scene" style={{clipPath:'inset(0 '+(100-compare)+'% 0 0)'}}/><div className="compare-line" style={{left:compare+'%'}}><span>↔</span></div><span className="image-label before">ORIGINAL</span><span className="image-label after">CURRENT</span></>}
       {mode!=='Compare'&&highlight&&!highlight.removed&&<div className="region" style={regionStyle(plan&&highlight.id===selected?box:highlight.box)}><span>{highlight.name}</span><i/><i/><i/><i/></div>}
     </div>{mode==='Compare'?<label className="compare-control">Original<input type="range" min="0" max="100" value={compare} onChange={e=>setCompare(Number(e.target.value))} aria-label="Before and after comparison"/>Current</label>:<div className="artwork-caption"><span>{mode==='Inspect'?'Hover to inspect · Click to select':'Click an object or choose an entity'}</span><span>v{scene.current+1} / {scene.versions.length}</span></div>}</div>}
     {layers.map(l=><div key={l.id} className={'canvas-element '+(!preview&&layerId===l.id?'layer-selected':'')} style={{left:l.x,top:l.y,width:l.width,height:l.height,transform:`rotate(${l.rotation||0}deg)`,'--handle-scale':1/zoom,'--selection-width':1/zoom+'px'}} onPointerDown={e=>beginDrag(e,l.id)}><div className="layer-content" style={{borderRadius:l.radius,opacity:l.opacity}}>{l.type==='image'?<img src={l.src} alt="Uploaded asset" draggable="false"/>:<div className="vector-layer" dangerouslySetInnerHTML={{__html:layerSvg(l)}}/>}</div>{!preview&&layerId===l.id&&<><div className="selection-dimensions" aria-hidden="true">{Math.round(l.width)} &times; {Math.round(l.height)}</div>{resizeHandles.map(([handle,label])=><button type="button" key={handle} className={'resize-handle handle-'+handle} disabled={busy} aria-label={'Resize '+label} title={'Drag to '+(handle.length===2?'scale proportionally. Hold Shift to resize freely.':'resize the container.')} onPointerDown={e=>beginResize(e,l.id,handle)} onKeyDown={e=>keyboardResize(e,l,handle)} onClick={e=>e.stopPropagation()}/>)}</>}</div>)}
     </div>
    </div>
    <section className="active-instruction"><label htmlFor="active-prompt"><Icon name="cube"/> ACTIVE PROJECT INSTRUCTION</label><div><textarea id="active-prompt" value={activePrompt} onChange={e=>setActivePrompt(e.target.value)} placeholder="Your creative direction lives here" rows="2"/><button disabled={busy||!activePrompt.trim()} onClick={()=>{setPrompt(activePrompt);setView('home');}}>Use prompt <span aria-hidden="true">&#8599;</span></button></div>{!busy&&error&&!scene&&<button onClick={()=>generate(activePrompt||prompt)}>Retry generation</button>}</section>
    <div className="canvas-status" role="status" aria-live="polite"><span className={busy?'spinner':'status-dot'}/><span>{status}</span>{job&&<button onClick={()=>safe(()=>api('/jobs/'+job,null,'DELETE'))}>Cancel</button>}<span className="engine">HY IMAGE 3.5 PREVIEW</span></div>
   </main>
   <aside className={'inspector '+(editableImage?'image-layer-inspector':'')}><div className="panel-heading"><span>{activeLayer?'PROPERTIES':entity?'ENTITY INSPECTOR':'PROPERTIES'}</span><button aria-label="Close properties" disabled={busy} onClick={()=>{setLayerId(null);setSelected(null);}}><Icon name="close"/></button></div>
    {activeLayer&&<fieldset className="property-fieldset" disabled={busy}><LayerProperties duplicate={()=>{const id=crypto.randomUUID();commit([...layers,{...activeLayer,id,x:activeLayer.x+24,y:activeLayer.y+24}]);setLayerId(id);}} arrange={where=>{const rest=layers.filter(l=>l.id!==layerId);commit(where==='front'?[...rest,activeLayer]:[activeLayer,...rest]);}} element={activeLayer} update={patch=>commit(layers.map(l=>l.id===layerId?{...l,...patch}:l))} remove={()=>{commit(layers.filter(l=>l.id!==layerId));setLayerId(null);}}/></fieldset>}
    {entity?<><div className="entity-heading"><span className="eyebrow">{entity.type}</span><h2>{entity.name}</h2><p>{entity.description}</p></div><div className="metadata"><span>Region</span><strong>Approximate rectangle</strong><span>Depth</span><strong>{entity.depth}</strong><span>Identity</span><strong title={entity.id}>{entity.id.slice(0,8)}</strong></div>{entity.relationships.length>0&&<div className="relationships"><span className="eyebrow">CONTEXT</span>{entity.relationships.map((r,i)=><p key={i}>{r}</p>)}</div>}</>:<div className="inspector-empty"><div className="selection-symbol"/><h2>One part.<br/>New possibilities.</h2><p>Select an object on the canvas, or describe what you want to change.</p></div>}
    <div className="edit-box"><label htmlFor="edit">DESCRIBE YOUR CHANGE</label><textarea id="edit" placeholder={editableImage?'Describe what to change in this image...':entity?'Make this '+entity.name.toLowerCase()+'…':'Make the Ferris wheel deep blue…'} value={instruction} onChange={e=>{setInstruction(e.target.value);setPlan(null);setLayerPlan(null);setPrepared(null);}} disabled={(!scene&&!editableImage)||busy} maxLength={2000} rows="4"/><div className="preserve-note"><span className="tiny-frame"/> {editableImage?'Only this image layer will change.':'Outside the approved region stays protected.'}</div><button className="primary full" disabled={(!scene&&!editableImage)||busy||instruction.trim().length<3||(!editableImage&&!config?.minimax)||!config?.hy.ready||!config?.cloudinary} onClick={changeSelectedImage}>{busy?'Applying edit...':'Apply edit'} <span>↗</span></button><button className="review-edit-button" disabled={(!scene&&!editableImage)||busy||instruction.trim().length<3||(!editableImage&&!config?.minimax)} onClick={prepareStable}>Review region before applying</button>{(!config?.hy.ready||!config?.cloudinary)&&<p className="inline-error">Image editing requires the image provider and Cloudinary to be configured.</p>}</div>
    <div className="edit-feedback" aria-live="polite">{busy&&<p>{status}</p>}{error&&<p role="alert" className="inline-error">{error}</p>}{!editableImage&&!config?.minimax&&<p>Image edit preparation requires the MiniMax provider to be configured.</p>}</div>
    {layerPlan&&editableImage&&<section className="plan"><span className="eyebrow">REVIEW IMAGE EDIT</span><img className="edit-reference" src={activeLayer.src} alt="Selected image to edit"/><p>{layerPlan.instruction}</p><small>{layerPlan.reason}</small><p className="small">The selected image is the editable region. Other Canvas layers stay unchanged.</p><button className="primary full" disabled={busy||!config?.hy.ready||!config?.cloudinary} onClick={applyLayer}>{busy?'Editing image...':'Apply edit to image'}</button>{(!config?.hy.ready||!config?.cloudinary)&&<p className="inline-error">Configure the image provider and Cloudinary before applying this edit.</p>}</section>}
    {plan&&!activeLayer&&box&&<div className="plan"><span className="eyebrow">REVIEW LOCALIZED EDIT</span><p>{plan.instruction}</p><small>{plan.reason}</small><label className="region-label">Approved region (%)</label><div className="region-inputs">{['x','y','width','height'].map(k=><label key={k}>{k}<input type="number" min="0" max="100" step="0.1" value={Math.round(box[k]*1000)/10} disabled={busy} onChange={e=>setBox({...box,[k]:Number(e.target.value)/100})}/></label>)}</div><p className="small">Review the rectangle carefully. It includes every pixel allowed to change. Expand it for moves, resizing or shadows.</p><button className="primary full" disabled={busy||!config?.hy.ready||!config?.cloudinary||box.width<=0||box.height<=0||box.x+box.width>1||box.y+box.height>1} onClick={apply}>Reframe {entity?.name}</button></div>}
    {entity?.editHistory.length>0&&<div className="entity-history"><span className="eyebrow">THIS ENTITY'S JOURNEY</span><p>Original</p>{entity.editHistory.map((h,i)=><p key={i}>↳ {h.instruction}</p>)}</div>}
    {scene?.analysisWarning&&<p className="analysis-warning" role="status">{scene.analysisWarning}</p>}
    {scene&&entities.length===0&&<button disabled={busy||!config?.minimax} onClick={()=>run(async()=>{const j=await api('/scenes/'+scene.id+'/analyze',{});await watch(j.jobId);})}>Analyze saved image</button>}
    <div className="inspector-foot"><span>Structured, not flattened.</span><p>Entity regions are AI estimates. Review their boundaries before each edit.</p></div>
   </aside>
  </div>
  <footer className="history-bar"><span className="eyebrow">VERSION HISTORY</span><div className="versions">{scene?scene.versions.map((v,i)=><button key={v.id} disabled={busy} className={scene.current===i?'current':''} title={v.label} onClick={()=>restore(v.id)}><span className="version-index">v{i+1}</span><span>{i===0?'Original scene':v.label}</span>{scene.current===i&&<span className="current-dot"/>}</button>):<span className="history-empty">Every reframe becomes a saved version.</span>}</div>{scene&&current.parentId&&<button disabled={busy} onClick={()=>restore(current.parentId)}>↶ Undo edit</button>}</footer>
  {config&&(!config.hy.ready||!config.minimax)&&<div className="setup-banner"><span className="setup-label">SETUP REQUIRED</span><span>{!config.hy.ready?'Configure GMI_API_KEY to generate scenes.':'Configure MiniMax M3 to analyze scenes.'}</span><button onClick={()=>setNewScene(true)}>View setup</button></div>}
  {error&&<div className="error-toast" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
  {newScene&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="new-title"><button className="close" aria-label="Close dialog" onClick={()=>setNewScene(false)}>×</button><span className="eyebrow">GAME ART / NEW SCENE</span><h2 id="new-title">Build a world worth keeping.</h2><p>Start with distinct structures, characters and details. Reframe will analyze the image after generation.</p><label htmlFor="prompt">Scene prompt</label><textarea autoFocus id="prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} rows="5" maxLength="4000"/><div className="model-line"><span>Hy Image 3.5 Preview</span><span>via GMI Cloud</span></div>{!canGenerate&&<div className="setup-details"><strong>Provider setup</strong><p>{config?.hy.reason||'Checking configuration…'}</p><ul><li>GMI: {config?.hy.ready?'Ready':'GMI_API_KEY required'}</li><li>MiniMax M3: {config?.minimax?'Key configured (not yet verified)':'ANTHROPIC_API_KEY required'}</li><li>Cloudinary: {config?.cloudinary?'Configured':'Optional for storage; required for edit reference URLs'}</li></ul><small>Configure server variables in .env. No simulated images or entities are used.</small></div>}<button className="primary full" disabled={!canGenerate||busy||prompt.trim().length<10} onClick={generate}>{busy?'Working…':'Generate scene'} <span>↗</span></button><small className="modal-note">Generation may take around 20 seconds; analysis follows.</small></section></div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
